#/appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/build
hooks:
  BeforeInstall:
    - location: /initailize.sh
      runas: root
  ApplicationStart:
    - location: /start.sh
      runas: root
